version: '3'

tasks:

  default:
    desc: Build and run the Go package
    cmds:
      - task: run
      - task: delete

  build:
    desc: Build the Go package
    cmds:
      - go mod tidy
      - go build -o ec 
        
  run:
    desc: Run the Go package
    cmds:
      - ./ec get deploymentManifest
      # - ./ec get deploymentManifests
      # - ./ec get deploymentManifestTemplate
      # - ./ec get deploymentManifestTemplates
      # - ./ec get deployments

    deps: [build]

  delete:
    desc: Delete the main executable
    cmds: 
      - rm ./ec