version: '3'

tasks:

  default:
    desc: Build and run the Go package
    cmds:
      - task: run
      - task: delete

  build:
    desc: Build the Go package
    cmds:
      - go mod tidy
      - |
        go build -o ec main.go \
        cbs-subscription.go \
        composite.go \
        deployment-manifest-template.go \
        deployment-manifest.go \
        deployment.go \
        inventory.go \
        jenkins.go \
        job.go \
        jobGroup.go \
        manifest-template.go \
        manifest.go \
        order-status.go \
        resource-template.go \
        sizing-script.go \
        subscription.go \

  run:
    desc: Run the Go package
    cmds:
      # - ./ec get manifests --database ec-provisioner
      # - ./ec get manifestTemplates --database ec-provisioner
      # - ./ec get deployments --database ec-provisioner

    deps: [build]

  delete:
    desc: Delete the main executable
    cmds: 
      - rm ./ec