version: '3'

tasks:

  default:
    desc: Build and run the Go package
    cmds:
      - task: run
      - task: delete

  build:
    desc: Build the Go package
    cmds:
      - go mod tidy
      - go mod download
      - go build -o ec-cli

  docker-build:
    desc: Build the docker image
    cmds:
      - read -p "You must disable zscaler internet security. Press Enter to continue."
      - echo "az acr login --name acraocpshsrvnonprod"
      - read -p "run the command above. Press Enter to continue."
      - go mod tidy
      - docker image build -t acraocpshsrvnonprod.azurecr.io/ec-cli .
      # - docker image build --no-cache -t acraocpshsrvnonprod.azurecr.io/ec-cli .
      # - az acr login --name acraocpshsrvnonprod
      - docker push acraocpshsrvnonprod.azurecr.io/ec-cli

  run:
    desc: Run the Go package
    cmds:
      - ./ec-cli get deploymentManifest
      # - ./ec-cli get deploymentManifests
      # - ./ec-cli get deploymentManifestTemplate
      # - ./ec-cli get deploymentManifestTemplates
      # - ./ec-cli get deployments

    deps: [build]

  delete:
    desc: Delete the main executable
    cmds: 
      - rm ./ec