version: '3'

tasks:

  default:
    desc: Build and run the Go package
    cmds:
      - task: run
      - task: delete

  build:
    desc: Build the Go package
    cmds:
      - go mod tidy
      - go build -o ec main.go manifest.go manifest-template.go deployment.go

  run:
    desc: Run the Go package
    cmds:
      - ./ec get manifests --database ec-provisioner
      # - ./ec get manifestTemplates --database ec-provisioner
      # - ./ec get deployments --database ec-provisioner

    deps: [build]

  delete:
    desc: Delete the main executable
    cmds: 
      - rm ./ec