version: '3'

tasks:

  default:
    desc: Build and run the Go package
    cmds:
      - task: build
      - task: run
      - task: delete

  build:
    desc: Build the Go package
    cmds:
      - go mod tidy
      - go build -o ec main.go manifest.go

  run:
    desc: Run the Go package
    cmds:
      - ./ec get manifest --container customer --database jjl-test --partitionKey /customer --name asdf
    deps: [build]

  delete:
    desc: Delete the main executable
    cmds: 
      - rm ./ec